truncate table Town

SET IDENTITY_INSERT [dbo].[Town] ON 

INSERT [dbo].[Town] ([Id], [CityId], [Name]) 
  VALUES (1, 1, N'ALADAĞ')
, (2, 1, N'CEYHAN')
, (3, 1, N'ÇUKUROVA')
, (4, 1, N'FEKE')
, (5, 1, N'İMAMOĞLU')
, (6, 1, N'KARAİSALI')
, (7, 1, N'KARATAŞ')
, (8, 1, N'KOZAN')
, (9, 1, N'POZANTI')
, (10, 1, N'SAİMBEYLİ')
, (11, 1, N'SARIÇAM')
, (12, 1, N'SEYHAN')
, (13, 1, N'TUFANBEYLİ')
, (14, 1, N'YUMURTALIK')
, (15, 1, N'YÜREĞİR')
, (16, 2, N'BESNİ')
, (17, 2, N'ÇELİKHAN')
, (18, 2, N'GERGER')
, (19, 2, N'GÖLBAŞI')
, (20, 2, N'KAHTA')
, (21, 2, N'SAMSAT')
, (22, 2, N'SİNCİK')
, (23, 2, N'TUT')
, (24, 3, N'BAŞMAKÇI')
, (25, 3, N'BAYAT')
, (26, 3, N'BOLVADİN')
, (27, 3, N'ÇAY')
, (28, 3, N'ÇOBANLAR')
, (29, 3, N'DAZKIRI')
, (30, 3, N'DİNAR')
, (31, 3, N'EMİRDAĞ')
, (32, 3, N'EVCİLER')
, (33, 3, N'HOCALAR')
, (34, 3, N'İHSANİYE')
, (35, 3, N'İSCEHİSAR')
, (36, 3, N'KIZILÖREN')
, (37, 3, N'SANDIKLI')
, (38, 3, N'SİNANPAŞA')
, (39, 3, N'SULTANDAĞI')
, (40, 3, N'ŞUHUT')
, (41, 4, N'DİYADİN')
, (42, 4, N'DOĞUBAYAZIT')
, (43, 4, N'ELEŞKİRT')
, (44, 4, N'HAMUR')
, (45, 4, N'PATNOS')
, (46, 4, N'TAŞLIÇAY')
, (47, 4, N'TUTAK')
, (48, 5, N'GÖYNÜCEK')
, (49, 5, N'GÜMÜŞHACIKÖY')
, (50, 5, N'HAMAMÖZÜ')
, (51, 5, N'MERZİFON')
, (52, 5, N'SULUOVA')
, (53, 5, N'TAŞOVA')
, (54, 6, N'AKYURT')
, (55, 6, N'ALTINDAĞ')
, (56, 6, N'AYAŞ')
, (57, 6, N'BALA')
, (58, 6, N'BEYPAZARI')
, (59, 6, N'ÇAMLIDERE')
, (60, 6, N'ÇANKAYA')
, (61, 6, N'ÇUBUK')
, (62, 6, N'ELMADAĞ')
, (63, 6, N'ETİMESGUT')
, (64, 6, N'EVREN')
, (65, 6, N'GÖLBAŞI')
, (66, 6, N'GÜDÜL')
, (67, 6, N'HAYMANA')
, (68, 6, N'KALECİK')
, (69, 6, N'KAZAN')
, (70, 6, N'KEÇİÖREN')
, (71, 6, N'KIZILCAHAMAM')
, (72, 6, N'MAMAK')
, (73, 6, N'NALLIHAN')
, (74, 6, N'POLATLI')
, (75, 6, N'PURSAKLAR')
, (76, 6, N'SİNCAN')
, (77, 6, N'ŞEREFLİKOÇHİSAR')
, (78, 6, N'YENİMAHALLE')
, (79, 7, N'AKSEKİ')
, (80, 7, N'AKSU')
, (81, 7, N'ALANYA')
, (82, 7, N'DEMRE')
, (83, 7, N'DÖŞEMEALTI')
, (84, 7, N'ELMALI')
, (85, 7, N'FİNİKE')
, (86, 7, N'GAZİPAŞA')
, (87, 7, N'GÜNDOĞMUŞ')
, (88, 7, N'İBRADI')
, (89, 7, N'KAŞ')
, (90, 7, N'KEMER')
, (91, 7, N'KEPEZ')
, (92, 7, N'KONYAALTI')
, (93, 7, N'KORKUTELİ')
, (94, 7, N'KUMLUCA')
, (95, 7, N'MANAVGAT')
, (96, 7, N'MURATPAŞA')
, (97, 7, N'SERİK')
, (98, 8, N'ARDANUÇ')
, (99, 8, N'ARHAVİ')
go

INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (100, 8, N'BORÇKA')
, (101, 8, N'HOPA')
, (102, 8, N'MURGUL')
, (103, 8, N'ŞAVŞAT')
, (104, 8, N'YUSUFELİ')
, (105, 9, N'BOZDOĞAN')
, (106, 9, N'BUHARKENT')
, (107, 9, N'ÇİNE')
, (108, 9, N'DİDİM')
, (109, 9, N'EFELER')
, (110, 9, N'GERMENCİK')
, (111, 9, N'İNCİRLİOVA')
, (112, 9, N'KARACASU')
, (113, 9, N'KARPUZLU')
, (114, 9, N'KOÇARLI')
, (115, 9, N'KÖŞK')
, (116, 9, N'KUŞADASI')
, (117, 9, N'KUYUCAK')
, (118, 9, N'NAZİLLİ')
, (119, 9, N'SÖKE')
, (120, 9, N'SULTANHİSAR')
, (121, 9, N'YENİPAZAR')
, (122, 10, N'ALTIEYLÜL')
, (123, 10, N'AYVALIK')
, (124, 10, N'BALYA')
, (125, 10, N'BANDIRMA')
, (126, 10, N'BİGADİÇ')
, (127, 10, N'BURHANİYE')
, (128, 10, N'DURSUNBEY')
, (129, 10, N'EDREMİT')
, (130, 10, N'ERDEK')
, (131, 10, N'GÖMEÇ')
, (132, 10, N'GÖNEN')
, (133, 10, N'HAVRAN')
, (134, 10, N'KARESİ')
, (135, 10, N'İVRİNDİ')
, (136, 10, N'KEPSUT')
, (137, 10, N'MANYAS')
, (138, 10, N'MARMARA')
, (139, 10, N'SAVAŞTEPE')
, (140, 10, N'SINDIRGI')
, (141, 10, N'SUSURLUK')
, (142, 11, N'BOZÜYÜK')
, (143, 11, N'GÖLPAZARI')
, (144, 11, N'İNHİSAR')
, (145, 11, N'OSMANELİ')
, (146, 11, N'PAZARYERİ')
, (147, 11, N'SÖĞÜT')
, (148, 11, N'YENİPAZAR')
, (149, 12, N'ADAKLI')
, (150, 12, N'GENÇ')
, (151, 12, N'KARLIOVA')
, (152, 12, N'KİĞI')
, (153, 12, N'SOLHAN')
, (154, 12, N'YAYLADERE')
, (155, 12, N'YEDİSU')
, (156, 13, N'ADİLCEVAZ')
, (157, 13, N'AHLAT')
, (158, 13, N'GÜROYMAK')
, (159, 13, N'HİZAN')
, (160, 13, N'MUTKİ')
, (161, 13, N'TATVAN')
, (162, 14, N'DÖRTDİVAN')
, (163, 14, N'GEREDE')
, (164, 14, N'GÖYNÜK')
, (165, 14, N'KIBRISCIK')
, (166, 14, N'MENGEN')
, (167, 14, N'MUDURNU')
, (168, 14, N'SEBEN')
, (169, 14, N'YENİÇAĞA')
, (170, 15, N'AĞLASUN')
, (171, 15, N'ALTINYAYLA')
, (172, 15, N'BUCAK')
, (173, 15, N'ÇAVDIR')
, (174, 15, N'ÇELTİKÇİ')
, (175, 15, N'GÖLHİSAR')
, (176, 15, N'KARAMANLI')
, (177, 15, N'KEMER')
, (178, 15, N'TEFENNİ')
, (179, 15, N'YEŞİLOVA')
, (180, 16, N'BÜYÜKORHAN')
, (181, 16, N'GEMLİK')
, (182, 16, N'GÜRSU')
, (183, 16, N'HARMANCIK')
, (184, 16, N'İNEGÖL')
, (185, 16, N'İZNİK')
, (186, 16, N'KARACABEY')
, (187, 16, N'KELES')
, (188, 16, N'KESTEL')
, (189, 16, N'MUDANYA')
, (190, 16, N'MUSTAFAKEMALPAŞA')
, (191, 16, N'NİLÜFER')
, (192, 16, N'ORHANELİ')
, (193, 16, N'ORHANGAZİ')
, (194, 16, N'OSMANGAZİ')
, (195, 16, N'YENİŞEHİR')
, (196, 16, N'YILDIRIM')
go

INSERT [dbo].[Town] ([Id], [CityId], [Name]) 
  VALUES (197, 17, N'AYVACIK')
, (198, 17, N'BAYRAMİÇ')
, (199, 17, N'BİGA')
, (200, 17, N'BOZCAADA')
, (201, 17, N'ÇAN')
, (202, 17, N'ECEABAT')
, (203, 17, N'EZİNE')
, (204, 17, N'GELİBOLU')
, (205, 17, N'MERKEZ')
, (206, 17, N'LAPSEKİ')
, (207, 17, N'YENİCE')
go



INSERT [dbo].[Town] ([Id], [CityId], [Name]) 
  VALUES (208, 18, N'ATKARACALAR')
, (209, 18, N'BAYRAMÖREN')
, (210, 18, N'ÇERKEŞ')
, (211, 18, N'ELDİVAN')
, (212, 18, N'ILGAZ')
, (213, 18, N'KIZILIRMAK')
, (214, 18, N'KORGUN')
, (215, 18, N'KURŞUNLU')
, (216, 18, N'ORTA')
, (217, 18, N'ŞABANÖZÜ')
, (218, 18, N'YAPRAKLI')
, (219, 19, N'ALACA')
, (220, 19, N'BAYAT')
, (221, 19, N'BOĞAZKALE')
, (222, 19, N'DODURGA')
, (223, 19, N'İSKİLİP')
, (224, 19, N'KARGI')
, (225, 19, N'LAÇİN')
, (226, 19, N'MECİTÖZÜ')
, (227, 19, N'OĞUZLAR')
, (228, 19, N'ORTAKÖY')
, (229, 19, N'OSMANCIK')
, (230, 19, N'SUNGURLU')
, (231, 19, N'UĞURLUDAĞ')
, (232, 20, N'ACIPAYAM')
, (234, 20, N'BABADAĞ')
, (235, 20, N'BAKLAN')
, (236, 20, N'BEKİLLİ')
, (237, 20, N'BEYAĞAÇ')
, (238, 20, N'BOZKURT')
, (239, 20, N'BULDAN')
, (240, 20, N'ÇAL')
, (241, 20, N'ÇAMELİ')
, (242, 20, N'ÇARDAK')
, (243, 20, N'ÇİVRİL')
, (244, 20, N'GÜNEY')
, (245, 20, N'HONAZ')
, (246, 20, N'KALE')
, (247, 20, N'MERKEZEFENDİ')
, (248, 20, N'SARAYKÖY')
, (249, 20, N'SERİNHİSAR')
, (250, 20, N'TAVAS')
, (251, 21, N'BAĞLAR')
, (252, 21, N'BİSMİL')
, (253, 21, N'ÇERMİK')
, (254, 21, N'ÇINAR')
, (255, 21, N'ÇÜNGÜŞ')
, (256, 21, N'DİCLE')
, (257, 21, N'EĞİL')
, (258, 21, N'ERGANİ')
, (259, 21, N'HANİ')
, (260, 21, N'HAZRO')
, (261, 21, N'KAYAPINAR')
, (262, 21, N'KOCAKÖY')
, (263, 21, N'KULP')
, (264, 21, N'LİCE')
, (265, 21, N'SİLVAN')
, (266, 21, N'SUR')
, (267, 21, N'YENİŞEHİR')
, (268, 22, N'ENEZ')
, (269, 22, N'HAVSA')
, (270, 22, N'İPSALA')
, (271, 22, N'KEŞAN')
, (272, 22, N'LALAPAŞA')
, (273, 22, N'MERİÇ')
, (274, 22, N'SÜLOĞLU')
, (275, 22, N'UZUNKÖPRÜ')
, (276, 23, N'AĞIN')
, (277, 23, N'ALACAKAYA')
, (278, 23, N'ARICAK')
, (279, 23, N'BASKİL')
, (280, 23, N'KARAKOÇAN')
, (281, 23, N'KEBAN')
, (282, 23, N'KOVANCILAR')
, (283, 23, N'MADEN')
, (284, 23, N'PALU')
, (285, 23, N'SİVRİCE')
, (286, 24, N'ÇAYIRLI')
, (287, 24, N'İLİÇ')
, (288, 24, N'KEMAH')
, (289, 24, N'KEMALİYE')
, (290, 24, N'OTLUKBELİ')
, (291, 24, N'REFAHİYE')
, (292, 24, N'TERCAN')
, (293, 24, N'ÜZÜMLÜ')
, (294, 25, N'AŞKALE')
, (295, 25, N'AZİZİYE')
, (296, 25, N'ÇAT')
, (297, 25, N'HINIS')
, (298, 25, N'HORASAN')
, (299, 25, N'İSPİR')
, (300, 25, N'KARAÇOBAN')
go

INSERT [dbo].[Town] ([Id], [CityId], [Name]) 
  VALUES (301, 25, N'KARAYAZI')
, (302, 25, N'KÖPRÜKÖY')
, (303, 25, N'NARMAN')
, (304, 25, N'OLTU')
, (305, 25, N'OLUR')
, (306, 25, N'PALANDÖKEN')
, (307, 25, N'PASİNLER')
, (308, 25, N'PAZARYOLU')
, (309, 25, N'ŞENKAYA')
, (310, 25, N'TEKMAN')
, (311, 25, N'TORTUM')
, (312, 25, N'UZUNDERE')
, (313, 25, N'YAKUTİYE')
, (314, 26, N'ALPU')
, (315, 26, N'BEYLİKOVA')
, (316, 26, N'ÇİFTELER')
, (317, 26, N'GÜNYÜZÜ')
, (318, 26, N'HAN')
, (319, 26, N'İNÖNÜ')
, (320, 26, N'MAHMUDİYE')
, (321, 26, N'MİHALGAZİ')
, (322, 26, N'MİHALIÇÇIK')
, (323, 26, N'ODUNPAZARI')
, (324, 26, N'SARICAKAYA')
, (325, 26, N'SEYİTGAZİ')
, (326, 26, N'SİVRİHİSAR')
, (327, 26, N'TEPEBAŞI')
, (328, 27, N'ARABAN')
, (329, 27, N'İSLAHİYE')
, (330, 27, N'KARKAMIŞ')
, (331, 27, N'NİZİP')
, (332, 27, N'NURDAĞI')
, (333, 27, N'OĞUZELİ')
, (334, 27, N'ŞAHİNBEY')
, (335, 27, N'ŞEHİTKAMİL')
, (336, 27, N'YAVUZELİ')
, (337, 28, N'ALUCRA')
, (338, 28, N'BULANCAK')
, (339, 28, N'ÇAMOLUK')
, (340, 28, N'ÇANAKÇI')
, (341, 28, N'DERELİ')
, (342, 28, N'DOĞANKENT')
, (343, 28, N'ESPİYE')
, (344, 28, N'EYNESİL')
, (345, 28, N'GÖRELE')
, (346, 28, N'GÜCE')
, (347, 28, N'KEŞAP')
, (348, 28, N'PİRAZİZ')
, (349, 28, N'ŞEBİNKARAHİSAR')
, (350, 28, N'TİREBOLU')
, (351, 28, N'YAĞLIDERE')
, (352, 29, N'KELKİT')
, (353, 29, N'KÖSE')
, (354, 29, N'KÜRTÜN')
, (355, 29, N'ŞİRAN')
, (356, 29, N'TORUL')
, (357, 30, N'ÇUKURCA')
, (358, 30, N'ŞEMDİNLİ')
, (359, 30, N'YÜKSEKOVA')
, (360, 31, N'ALTINÖZÜ')
, (361, 31, N'ANTAKYA')
, (362, 31, N'ARSUZ')
, (363, 31, N'BELEN')
, (364, 31, N'DEFNE')
, (365, 31, N'DÖRTYOL')
, (366, 31, N'ERZİN')
, (367, 31, N'HASSA')
, (368, 31, N'İSKENDERUN')
, (369, 31, N'KIRIKHAN')
, (370, 31, N'KUMLU')
, (371, 31, N'PAYAS')
, (372, 31, N'REYHANLI')
, (373, 31, N'SAMANDAĞ')
, (374, 31, N'YAYLADAĞI')
, (375, 32, N'AKSU')
, (376, 32, N'ATABEY')
, (377, 32, N'EĞİRDİR')
, (378, 32, N'GELENDOST')
, (379, 32, N'GÖNEN')
, (380, 32, N'KEÇİBORLU')
, (381, 32, N'SENİRKENT')
, (382, 32, N'SÜTÇÜLER')
, (383, 32, N'ŞARKİKARAAĞAÇ')
, (384, 32, N'ULUBORLU')
, (385, 32, N'YALVAÇ')
, (386, 32, N'YENİŞARBADEMLİ')
, (387, 33, N'AKDENİZ')
, (388, 33, N'ANAMUR')
, (389, 33, N'AYDINCIK')
, (390, 33, N'BOZYAZI')
, (391, 33, N'ÇAMLIYAYLA')
, (392, 33, N'ERDEMLİ')
, (393, 33, N'GÜLNAR')
, (394, 33, N'MEZİTLİ')
, (395, 33, N'MUT')
, (396, 33, N'SİLİFKE')
, (397, 33, N'TARSUS')
, (398, 33, N'TOROSLAR')
, (399, 33, N'YENİŞEHİR')
, (400, 34, N'ADALAR')
go

INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (401, 34, N'ARNAVUTKÖY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (402, 34, N'ATAŞEHİR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (403, 34, N'AVCILAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (404, 34, N'BAĞCILAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (405, 34, N'BAHÇELİEVLER')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (406, 34, N'BAKIRKÖY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (407, 34, N'BAŞAKŞEHİR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (408, 34, N'BAYRAMPAŞA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (409, 34, N'BEŞİKTAŞ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (410, 34, N'BEYKOZ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (411, 34, N'BEYLİKDÜZÜ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (412, 34, N'BEYOĞLU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (413, 34, N'BÜYÜKÇEKMECE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (414, 34, N'ÇATALCA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (415, 34, N'ÇEKMEKÖY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (416, 34, N'ESENLER')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (417, 34, N'ESENYURT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (418, 34, N'EYÜP')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (419, 34, N'FATİH')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (420, 34, N'GAZİOSMANPAŞA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (421, 34, N'GÜNGÖREN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (422, 34, N'KADIKÖY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (423, 34, N'KAĞITHANE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (424, 34, N'KARTAL')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (425, 34, N'KÜÇÜKÇEKMECE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (426, 34, N'MALTEPE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (427, 34, N'PENDİK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (428, 34, N'SANCAKTEPE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (429, 34, N'SARIYER')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (430, 34, N'SİLİVRİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (431, 34, N'SULTANBEYLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (432, 34, N'SULTANGAZİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (433, 34, N'ŞİLE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (434, 34, N'ŞİŞLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (435, 34, N'TUZLA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (436, 34, N'ÜMRANİYE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (437, 34, N'ÜSKÜDAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (438, 34, N'ZEYTİNBURNU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (439, 35, N'ALİAĞA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (440, 35, N'BALÇOVA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (441, 35, N'BAYINDIR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (442, 35, N'BAYRAKLI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (443, 35, N'BERGAMA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (444, 35, N'BEYDAĞ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (445, 35, N'BORNOVA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (446, 35, N'BUCA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (447, 35, N'ÇEŞME')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (448, 35, N'ÇİĞLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (449, 35, N'DİKİLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (450, 35, N'FOÇA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (451, 35, N'GAZİEMİR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (452, 35, N'GÜZELBAHÇE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (453, 35, N'KARABAĞLAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (454, 35, N'KARABURUN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (455, 35, N'KARŞIYAKA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (456, 35, N'KEMALPAŞA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (457, 35, N'KINIK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (458, 35, N'KİRAZ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (459, 35, N'KONAK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (460, 35, N'MENDERES')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (461, 35, N' MENEMEN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (462, 35, N'NARLIDERE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (463, 35, N'ÖDEMİŞ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (464, 35, N'SEFERİHİSAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (465, 35, N'SELÇUK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (466, 35, N'TİRE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (467, 35, N'TORBALI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (468, 35, N'URLA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (469, 36, N'AKYAKA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (470, 36, N'ARPAÇAY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (471, 36, N'DİGOR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (472, 36, N'KAĞIZMAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (473, 36, N'SARIKAMIŞ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (474, 36, N'SELİM')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (475, 36, N'SUSUZ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (476, 37, N'ABANA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (477, 37, N'AĞLI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (478, 37, N'ARAÇ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (479, 37, N'AZDAVAY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (480, 37, N'BOZKURT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (481, 37, N'CİDE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (482, 37, N'ÇATALZEYTİN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (483, 37, N'DADAY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (484, 37, N'DEVREKANİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (485, 37, N'DOĞANYURT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (486, 37, N'HANÖNÜ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (487, 37, N'İHSANGAZİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (488, 37, N'İNEBOLU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (489, 37, N'KÜRE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (490, 37, N'PINARBAŞI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (491, 37, N'SEYDİLER')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (492, 37, N'ŞENPAZAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (493, 37, N'TAŞKÖPRÜ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (494, 37, N'TOSYA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (495, 38, N'AKKIŞLA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (496, 38, N'BÜNYAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (497, 38, N'DEVELİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (498, 38, N'FELAHİYE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (499, 38, N'HACILAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (500, 38, N'İNCESU')
GO
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (501, 38, N'KOCASİNAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (502, 38, N'MELİKGAZİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (503, 38, N'ÖZVATAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (504, 38, N'PINARBAŞI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (505, 38, N'SARIOĞLAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (506, 38, N'SARIZ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (507, 38, N'TALAS')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (508, 38, N'TOMARZA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (509, 38, N'YAHYALI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (510, 38, N'YEŞİLHİSAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (511, 39, N'BABAESKİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (512, 39, N'DEMİRKÖY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (513, 39, N'KOFÇAZ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (514, 39, N'LÜLEBURGAZ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (515, 39, N'PEHLİVANKÖY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (516, 39, N'PINARHİSAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (517, 39, N'VİZE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (518, 40, N'AKÇAKENT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (519, 40, N'AKPINAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (520, 40, N'BOZTEPE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (521, 40, N'ÇİÇEKDAĞI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (522, 40, N'KAMAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (523, 40, N'MUCUR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (524, 41, N'BAŞİSKELE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (525, 41, N'ÇAYIROVA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (526, 41, N'DARICA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (527, 41, N'DERİNCE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (528, 41, N'DİLOVASI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (529, 41, N'GEBZE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (530, 41, N'GÖLCÜK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (531, 41, N'İZMİT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (532, 41, N'KANDIRA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (533, 41, N'KARAMÜRSEL')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (534, 41, N'KARTEPE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (535, 41, N'KÖRFEZ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (536, 42, N'AHIRLI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (537, 42, N'AKÖREN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (538, 42, N'AKŞEHİR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (539, 42, N'ALTINEKİN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (540, 42, N'BEYŞEHİR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (541, 42, N'BOZKIR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (542, 42, N'CİHANBEYLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (543, 42, N'ÇELTİK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (544, 42, N'ÇUMRA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (545, 42, N'DERBENT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (546, 42, N'DEREBUCAK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (547, 42, N'DOĞANHİSAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (548, 42, N'EMİRGAZİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (549, 42, N'EREĞLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (550, 42, N'GÜNEYSINIR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (551, 42, N'HADİM')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (552, 42, N'HALKAPINAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (553, 42, N'HÜYÜK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (554, 42, N'ILGIN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (555, 42, N'KADINHANI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (556, 42, N'KARAPINAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (557, 42, N'KARATAY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (558, 42, N'KULU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (559, 42, N'MERAM')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (560, 42, N'SARAYÖNÜ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (561, 42, N'SELÇUKLU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (562, 42, N'SEYDİŞEHİR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (563, 42, N'TAŞKENT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (564, 42, N'TUZLUKÇU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (565, 42, N'YALIHÜYÜK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (566, 42, N'YUNAK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (567, 43, N'ALTINTAŞ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (568, 43, N'ASLANAPA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (569, 43, N'ÇAVDARHİSAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (570, 43, N'DOMANİÇ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (571, 43, N'DUMLUPINAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (572, 43, N'EMET')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (573, 43, N'GEDİZ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (574, 43, N'HİSARCIK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (575, 43, N'PAZARLAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (576, 43, N'SİMAV')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (577, 43, N'ŞAPHANE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (578, 43, N'TAVŞANLI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (579, 44, N'AKÇADAĞ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (580, 44, N'ARAPGİR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (581, 44, N'ARGUVAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (582, 44, N'BATTALGAZİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (583, 44, N'DARENDE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (584, 44, N'DOĞANŞEHİR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (585, 44, N'DOĞANYOL')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (586, 44, N'HEKİMHAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (587, 44, N'KALE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (588, 44, N'KULUNCAK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (589, 44, N'PÜTÜRGE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (590, 44, N'YAZIHAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (591, 44, N'YEŞİLYURT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (592, 45, N'AHMETLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (593, 45, N'AKHİSAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (594, 45, N'ALAŞEHİR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (595, 45, N'DEMİRCİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (596, 45, N'GÖLMARMARA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (597, 45, N'GÖRDES')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (598, 45, N'KIRKAĞAÇ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (599, 45, N'KÖPRÜBAŞI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (600, 45, N'KULA')
GO
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (601, 45, N'SALİHLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (602, 45, N'SARIGÖL')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (603, 45, N'SARUHANLI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (604, 45, N'SELENDİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (605, 45, N'ŞEHZADELER')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (606, 45, N'SOMA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (607, 45, N'TURGUTLU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (608, 45, N'YUNUSEMRE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (609, 46, N'AFŞİN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (610, 46, N'ANDIRIN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (611, 46, N'ÇAĞLAYANCERİT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (612, 46, N'DULKADİROĞLU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (613, 46, N'EKİNÖZÜ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (614, 46, N'ELBİSTAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (615, 46, N'GÖKSUN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (616, 46, N'NURHAK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (617, 46, N'ONİKİŞUBAT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (618, 46, N'PAZARCIK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (619, 46, N'TÜRKOĞLU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (620, 47, N'ARTUKLU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (621, 47, N'DARGEÇİT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (622, 47, N'DERİK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (623, 47, N'KIZILTEPE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (624, 47, N'MAZIDAĞI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (625, 47, N'MİDYAT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (626, 47, N'NUSAYBİN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (627, 47, N'ÖMERLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (628, 47, N'SAVUR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (629, 47, N'YEŞİLLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (630, 48, N'BODRUM')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (631, 48, N'DALAMAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (632, 48, N'DATÇA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (633, 48, N'FETHİYE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (634, 48, N'KAVAKLIDERE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (635, 48, N'KÖYCEĞİZ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (636, 48, N'MARMARİS')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (637, 48, N'MENTEŞE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (638, 48, N'MİLAS')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (639, 48, N'ORTACA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (640, 48, N'SEYDİKEMER')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (641, 48, N'ULA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (642, 48, N'YATAĞAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (643, 49, N'BULANIK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (644, 49, N'HASKÖY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (645, 49, N'KORKUT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (646, 49, N'MALAZGİRT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (647, 49, N'VARTO')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (648, 50, N'ACIGÖL')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (649, 50, N'AVANOS')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (650, 50, N'DERİNKUYU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (651, 50, N'GÜLŞEHİR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (652, 50, N'HACIBEKTAŞ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (653, 50, N'KOZAKLI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (654, 50, N'ÜRGÜP')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (655, 51, N'ALTUNHİSAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (656, 51, N'BOR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (657, 51, N'ÇAMARDI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (658, 51, N'ÇİFTLİK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (659, 51, N'ULUKIŞLA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (660, 52, N'AKKUŞ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (661, 52, N'ALTINORDU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (662, 52, N'AYBASTI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (663, 52, N'ÇAMAŞ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (664, 52, N'ÇATALPINAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (665, 52, N'ÇAYBAŞI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (666, 52, N'FATSA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (667, 52, N'GÖLKÖY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (668, 52, N'GÜLYALI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (669, 52, N'GÜRGENTEPE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (670, 52, N'İKİZCE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (671, 52, N'KABADÜZ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (672, 52, N'KABATAŞ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (673, 52, N'KORGAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (674, 52, N'KUMRU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (675, 52, N'MESUDİYE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (676, 52, N'PERŞEMBE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (677, 52, N'ULUBEY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (678, 52, N'ÜNYE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (679, 53, N'ARDEŞEN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (680, 53, N'ÇAMLIHEMŞİN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (681, 53, N'ÇAYELİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (682, 53, N'DEREPAZARI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (683, 53, N'FINDIKLI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (684, 53, N'GÜNEYSU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (685, 53, N'HEMŞİN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (686, 53, N'İKİZDERE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (687, 53, N'İYİDERE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (688, 53, N'KALKANDERE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (689, 53, N'PAZAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (690, 54, N'ADAPAZARI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (691, 54, N'AKYAZI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (692, 54, N'ARİFİYE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (693, 54, N'ERENLER')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (694, 54, N'FERİZLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (695, 54, N'GEYVE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (696, 54, N'HENDEK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (697, 54, N'KARAPÜRÇEK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (698, 54, N'KARASU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (699, 54, N'KAYNARCA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (700, 54, N'KOCAALİ')
GO
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (701, 54, N'PAMUKOVA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (702, 54, N'SAPANCA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (703, 54, N'SERDİVAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (704, 54, N'SÖĞÜTLÜ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (705, 54, N'TARAKLI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (706, 55, N'19 MAYIS')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (707, 55, N'ALAÇAM')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (708, 55, N'ASARCIK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (709, 55, N'ATAKUM')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (710, 55, N'AYVACIK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (711, 55, N'BAFRA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (712, 55, N'CANİK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (713, 55, N'ÇARŞAMBA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (714, 55, N'HAVZA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (715, 55, N'İLKADIM')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (716, 55, N'KAVAK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (717, 55, N'LADİK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (718, 55, N'SALIPAZARI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (719, 55, N'TEKKEKÖY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (720, 55, N'TERME')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (721, 55, N'VEZİRKÖPRÜ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (722, 55, N'YAKAKENT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (723, 56, N'AYDINLAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (724, 56, N'BAYKAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (725, 56, N'ERUH')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (726, 56, N'KURTALAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (727, 56, N'PERVARİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (728, 56, N'ŞİRVAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (729, 57, N'AYANCIK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (730, 57, N'BOYABAT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (731, 57, N'DİKMEN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (732, 57, N'DURAĞAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (733, 57, N'ERFELEK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (734, 57, N'GERZE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (735, 57, N'SARAYDÜZÜ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (736, 57, N'TÜRKELİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (737, 58, N'AKINCILAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (738, 58, N'ALTINYAYLA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (739, 58, N'DİVRİĞİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (740, 58, N'DOĞANŞAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (741, 58, N'GEMEREK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (742, 58, N'GÖLOVA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (743, 58, N'GÜRÜN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (744, 58, N'HAFİK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (745, 58, N'İMRANLI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (746, 58, N'KANGAL')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (747, 58, N'KOYULHİSAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (748, 58, N'SUŞEHRİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (749, 58, N'ŞARKIŞLA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (750, 58, N'ULAŞ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (751, 58, N'YILDIZELİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (752, 58, N'ZARA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (753, 59, N'ÇERKEZKÖY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (754, 59, N'ÇORLU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (755, 59, N'ERGENE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (756, 59, N'HAYRABOLU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (757, 59, N'KAPAKLI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (758, 59, N'MALKARA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (759, 59, N'MARMARAEREĞLİSİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (760, 59, N'MURATLI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (761, 59, N'SÜLEYMANPAŞA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (762, 59, N'SARAY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (763, 59, N'ŞARKÖY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (764, 60, N'ALMUS')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (765, 60, N'ARTOVA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (766, 60, N'BAŞÇİFTLİK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (767, 60, N'ERBAA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (768, 60, N'NİKSAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (769, 60, N'PAZAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (770, 60, N'REŞADİYE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (771, 60, N'SULUSARAY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (772, 60, N'TURHAL')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (773, 60, N'YEŞİLYURT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (774, 60, N'ZİLE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (775, 61, N'AKÇAABAT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (776, 61, N'ARAKLI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (777, 61, N'ARSİN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (778, 61, N'BEŞİKDÜZÜ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (779, 61, N'ÇARŞIBAŞI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (780, 61, N'ÇAYKARA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (781, 61, N'DERNEKPAZARI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (782, 61, N'DÜZKÖY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (783, 61, N'HAYRAT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (784, 61, N'KÖPRÜBAŞI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (785, 61, N'MAÇKA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (786, 61, N'OF')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (787, 61, N'ORTAHİSAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (788, 61, N'SÜRMENE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (789, 61, N'ŞALPAZARI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (790, 61, N'TONYA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (791, 61, N'VAKFIKEBİR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (792, 61, N'YOMRA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (793, 62, N'ÇEMİŞGEZEK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (794, 62, N'HOZAT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (795, 62, N'MAZGİRT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (796, 62, N'NAZIMİYE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (797, 62, N'OVACIK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (798, 62, N'PERTEK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (799, 62, N'PÜLÜMÜR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (800, 63, N'AKÇAKALE')
GO
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (801, 63, N'BİRECİK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (802, 63, N'BOZOVA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (803, 63, N'CEYLANPINAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (804, 63, N'EYYÜBİYE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (805, 63, N'HALFETİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (806, 63, N'HALİLİYE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (807, 63, N'HARRAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (808, 63, N'HİLVAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (809, 63, N'KARAKÖPRÜ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (810, 63, N'SİVEREK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (811, 63, N'SURUÇ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (812, 63, N'VİRANŞEHİR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (813, 64, N'BANAZ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (814, 64, N'EŞME')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (815, 64, N'KARAHALLI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (816, 64, N'SİVASLI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (817, 64, N'ULUBEY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (818, 65, N'BAHÇESARAY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (819, 65, N'BAŞKALE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (820, 65, N'ÇALDIRAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (821, 65, N'ÇATAK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (822, 65, N'EDREMİT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (823, 65, N'ERCİŞ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (824, 65, N'GEVAŞ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (825, 65, N'GÜRPINAR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (826, 65, N'İPEKYOLU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (827, 65, N'MURADİYE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (828, 65, N'ÖZALP')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (829, 65, N'SARAY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (830, 65, N'TUŞBA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (831, 66, N'AKDAĞMADENİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (832, 66, N'AYDINCIK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (833, 66, N'BOĞAZLIYAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (834, 66, N'ÇANDIR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (835, 66, N'ÇAYIRALAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (836, 66, N'ÇEKEREK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (837, 66, N'KADIŞEHRİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (838, 66, N'SARAYKENT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (839, 66, N'SARIKAYA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (840, 66, N'SORGUN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (841, 66, N'ŞEFAATLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (842, 66, N'YENİFAKILI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (843, 66, N'YERKÖY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (844, 67, N'ALAPLI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (845, 67, N'ÇAYCUMA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (846, 67, N'DEVREK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (847, 67, N'EREĞLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (848, 67, N'GÖKÇEBEY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (849, 67, N'KİLİMLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (850, 67, N'KOZLU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (851, 68, N'AĞAÇÖREN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (852, 68, N'ESKİL')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (853, 68, N'GÜLAĞAÇ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (854, 68, N'GÜZELYURT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (855, 68, N'ORTAKÖY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (856, 68, N'SARIYAHŞİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (857, 69, N'AYDINTEPE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (858, 69, N'DEMİRÖZÜ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (859, 70, N'AYRANCI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (860, 70, N'BAŞYAYLA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (861, 70, N'ERMENEK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (862, 70, N'KAZIMKARABEKİR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (863, 70, N'SARIVELİLER')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (864, 71, N'BAHŞİLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (865, 71, N'BALIŞEYH')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (866, 71, N'ÇELEBİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (867, 71, N'DELİCE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (868, 71, N'KARAKEÇİLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (869, 71, N'KESKİN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (870, 71, N'SULAKYURT')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (871, 71, N'YAHŞİHAN')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (872, 72, N'BEŞİRİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (873, 72, N'GERCÜŞ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (874, 72, N'HASANKEYF')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (875, 72, N'KOZLUK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (876, 72, N'SASON')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (877, 73, N'BEYTÜŞŞEBAP')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (878, 73, N'CİZRE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (879, 73, N'GÜÇLÜKONAK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (880, 73, N'İDİL')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (881, 73, N'SİLOPİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (882, 73, N'ULUDERE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (883, 74, N'AMASRA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (884, 74, N'KURUCAŞİLE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (885, 74, N'ULUS')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (886, 75, N'ÇILDIR')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (887, 75, N'DAMAL')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (888, 75, N'GÖLE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (889, 75, N'HANAK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (890, 75, N'POSOF')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (891, 76, N'ARALIK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (892, 76, N'KARAKOYUNLU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (893, 76, N'TUZLUCA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (894, 77, N'ALTINOVA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (895, 77, N'ARMUTLU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (896, 77, N'ÇINARCIK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (897, 77, N'ÇİFTLİKKÖY')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (898, 77, N'TERMAL')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (899, 78, N'EFLANİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (900, 78, N'ESKİPAZAR')
GO
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (901, 78, N'OVACIK')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (902, 78, N'SAFRANBOLU')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (903, 78, N'YENİCE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (904, 79, N'ELBEYLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (905, 79, N'MUSABEYLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (906, 79, N'POLATELİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (907, 80, N'BAHÇE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (908, 80, N'DÜZİÇİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (909, 80, N'HASANBEYLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (910, 80, N'KADİRLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (911, 80, N'SUMBAS')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (912, 80, N'TOPRAKKALE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (913, 81, N'AKÇAKOCA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (914, 81, N'CUMAYERİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (915, 81, N'ÇİLİMLİ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (916, 81, N'GÖLYAKA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (917, 81, N'GÜMÜŞOVA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (918, 81, N'KAYNAŞLI')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (919, 81, N'YIĞILCA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (920, 77, N'MERKEZ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (921, 20, N'PAMUKKALE')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (922, 17, N'GÖKÇEADA')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (923, 39, N'MERKEZ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (924, 5, N'MERKEZ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (925, 74, N'MERKEZ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (926, 19, N'MERKEZ')
INSERT [dbo].[Town] ([Id], [CityId], [Name]) VALUES (927, 32, N'MERKEZ')
SET IDENTITY_INSERT [dbo].[Town] OFF
